# 🐼 100 Pandas Practical Questions
> **Instructions:** Try to solve each question on your own. Use the hints only if you are stuck.  
> Progress: Basic → Intermediate → Advanced  
> Recommended pace: 10–15 questions per day

---

In [ ]:
import pandas as pd
import numpy as np

## 🔹 Section 1: Basics & Series (Q1–Q20)

---

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

---

In [ ]:
ser = pd.Series([1,2,3,4,5])
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

---

In [ ]:
ser = pd.Series({'marks': [40,50,60]})
ser

marks    [40, 50, 60]
dtype: object

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

---

In [ ]:
s = pd.Series({'a': 40, 'b': 50, 'c': 60})
s
s['a']
s[['a','b']]
s['a' : 'c']

a    40
b    50
c    60
dtype: int64

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

---

In [ ]:
s + 10
s - 10
s * 10
s / 10
s // 10
s % 10
s ** 10

a     10485760000000000
b     97656250000000000
c    604661760000000000
dtype: int64

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

---

In [ ]:
s.mean()
s.min()
s.max()
s.sum()
s.median()
s.std()

10.0

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

---

In [ ]:
s[s > 50]

c    60
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

---

In [ ]:
s.replace({40 : 70 , 50 : 80})

a    70
b    80
c    60
dtype: int64

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

---

In [ ]:
s.dtype
s.astype(int)
s.astype(float)
s.astype('category')

a    40
b    50
c    60
dtype: category
Categories (3, int64): [40, 50, 60]

### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

---

In [ ]:
a = pd.Series([10,np.nan,20,30,np.nan,40])
a
a.isnull()
a.isnull().sum()

np.int64(2)

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

---

In [ ]:
a.fillna(0)
a.fillna(a.mean())
a.ffill()
a.bfill()

0    10.0
1    20.0
2    20.0
3    30.0
4    40.0
5    40.0
dtype: float64

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

---

In [ ]:
df = pd.DataFrame([[5 , 'x'],[10 , 'y']], columns=['id','name'])
df

   id name
0   5    x
1  10    y

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

---

In [ ]:
df = pd.DataFrame({'id': [1,2,3],'name':['x','y','z']})
df

   id name
0   1    x
1   2    y
2   3    z

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

---

In [ ]:
df = pd.DataFrame([{'id': 1 , 'name': 'x'},{'id': 2 , 'name': 'y'}])
df

   id name
0   1    x
1   2    y

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

---

In [ ]:
df.shape
df.columns
df.dtypes
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      2 non-null      int64
 1   name    2 non-null      object
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

             id
count  2.000000
mean   1.500000
std    0.707107
min    1.000000
25%    1.250000
50%    1.500000
75%    1.750000
max    2.000000

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

---

In [ ]:
df['name']

0    x
1    y
Name: name, dtype: object

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

---

In [ ]:
df[['id','name']]

   id name
0   1    x
1   2    y

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

---

In [ ]:
df['score'] = 10
df

   id name  score
0   1    x     10
1   2    y     10

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

---

In [ ]:
df

   id  name  score
0   1    10     10
1   2    10     10

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

---

In [ ]:
df.rename(columns={'score' : 'score1'},inplace=True)
df

   id name  score1
0   1    x      10
1   2    y      10

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

---

In [ ]:
df.rename(columns={'id' : 'ID', 'Score1' : 'score1'})

   ID name  score1
0   1    x      10
1   2    y      10

## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

---

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

---

In [ ]:
marks = [40,50,60]
subjects = ['phy','chem','maths']
a = pd.DataFrame(marks,index= subjects)
a.loc['phy']
a.loc['phy':'maths']

        0
phy    40
chem   50
maths  60

### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

---

In [ ]:
a.iloc[0]
a.iloc[1:4]

        0
chem   50
maths  60

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

---

In [ ]:
a.loc['maths', 0]

np.int64(60)

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

---

In [ ]:
df.loc[0:1,['id','score1']]

   id  score1
0   1      10
1   2      10

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

---

In [ ]:
a.rename(columns={0 : 'marks'},inplace=True)

a.loc[a['marks'] > 40]

       marks
chem      50
maths     60

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

---

In [ ]:
a.iloc[0:3]

a.loc['phy':'maths']

       marks
phy       40
chem      50
maths     60

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

---

In [ ]:
df.loc[:,'ID' : 'score1']

   id name  score1
0   1    x      10
1   2    y      10

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

---

In [ ]:
df.iloc[:,1:4]

  name  score1
0    x      10
1    y      10

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

---

In [ ]:
df.loc[0:1,['id','score1']]

   id  score1
0   1      10
1   2      10

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

---

In [ ]:
df.set_index('id')

   name  score1
id
1     x      10
2     y      10

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

---

In [ ]:
df.set_index(['name','score1'])

             id
name score1
x    10       1
y    10       2

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

---

In [ ]:
df.reset_index()

   index  id name  score1
0      0   1    x      10
1      1   2    y      10

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

---

In [ ]:
df.reset_index()

   index  id name  score1
0      0   1    x      10
1      1   2    y      10

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

---

In [ ]:
df.reset_index(drop=False)

   index  id name  score1
0      0   1    x      10
1      1   2    y      10

### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

---

In [ ]:
df.reset_index(drop=True)

   id name  score1
0   1    x      10
1   2    y      10

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

---

In [ ]:
a

a.loc['maths']

marks    60
Name: maths, dtype: int64

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

---

In [ ]:
df.iloc[0]

id         1
name       x
score1    10
Name: 0, dtype: object

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

---

In [ ]:
a.head(1)

     marks
phy     40

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

---

In [ ]:
a.tail(1)

       marks
maths     60

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

---

## 🔹 Section 3: Data Cleaning (Q41–Q60)

---

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

---

In [ ]:
sam = pd.DataFrame({'A': [1, 2, np.nan, 4] , 'B': [5, np.nan, np.nan, 8]})
sam.isnull()
sam.isnull().sum()
sam.isnull().any()

A    True
B    True
dtype: bool

### Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

---

In [ ]:
sam.dropna()
sam.dropna(axis=1)
sam.dropna(subset=['A'])

     A    B
0  1.0  5.0
1  2.0  NaN
3  4.0  8.0

### Q43. Fill missing values with a constant.
> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

---

In [ ]:
sam.fillna(0)

     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  0.0
3  4.0  8.0

### Q44. Fill missing values using mean/median.
> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

---

In [ ]:
sam['B'].fillna(sam['B'].mean())
sam['B'].fillna(sam['B'].median())

0    5.0
1    6.5
2    6.5
3    8.0
Name: B, dtype: float64

### Q45. Use forward fill and backward fill.
> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

---

In [ ]:
sam.ffill()
sam.bfill()

     A    B
0  1.0  5.0
1  2.0  8.0
2  4.0  8.0
3  4.0  8.0

### Q46. Convert data type using `astype()`.
> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

---

In [ ]:
a['marks'].astype(int)

phy      40
chem     50
maths    60
Name: marks, dtype: int64

### Q47. Clean string column using `.str.lower()`.
> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

---

In [ ]:
data = pd.DataFrame({'name': ['Ajay more','Subodh savarekar','Swapnil tambe']})
data
data['name'].str.lower()
data['name'].str.upper()
data['name'].str.title()

0           Ajay More
1    Subodh Savarekar
2       Swapnil Tambe
Name: name, dtype: object

### Q48. Trim whitespace in strings.
> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

---

In [ ]:
data['name'].str.strip()
data['name'].str.lstrip()
data['name'].str.rstrip()

0           Ajay more
1    Subodh savarekar
2       Swapnil tambe
Name: name, dtype: object

### Q49. Replace substring in column.
> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

---

In [ ]:
data['name'].str.replace('Subodh savarekar','Mahesh jadhav',regex=True)

0        Ajay more
1    Mahesh jadhav
2    Swapnil tambe
Name: name, dtype: object

### Q50. Extract part of string using `.str`.
> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

---

In [ ]:
data['name'].str[:3]
data['name'].str.split('@').str[1]

0   NaN
1   NaN
2   NaN
Name: name, dtype: float64

### Q51. Detect duplicate rows.
> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

---

In [ ]:
data1 = pd.DataFrame({'name': ['ajay','subodh','swapnil','ajay'] , 'age': [30,31,29,30]})
data1[data1.duplicated()]

   name  age
3  ajay   30

### Q52. Remove duplicates using `drop_duplicates()`.
> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

---

In [ ]:
data1.drop_duplicates()
data1.drop_duplicates(subset=['name'],keep='last')

      name  age
1   subodh   31
2  swapnil   29
3     ajay   30

### Q53. Rename row labels.
> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

---

In [ ]:
a
a.rename(index={'phy' : 'bio'})

       marks
bio       40
chem      50
maths     60

### Q54. Handle inconsistent data.
> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

---

In [ ]:
data['name'].str.strip().str.lower()

0           ajay more
1    subodh savarekar
2       swapnil tambe
Name: name, dtype: object

### Q55. Replace values in DataFrame.
> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

---

In [ ]:
data1

data1.replace('ajay' , 'aj')
data1.replace({'swapnil':'dadus'})

     name  age
0    ajay   30
1  subodh   31
2   dadus   29
3    ajay   30

### Q56. Detect outliers in a column.
> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

---

In [ ]:
df = pd.DataFrame({'salary':[10000,20000,30000,40000,50000,60000]})
df

Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

below = Q1 - 1.5 * IQR
above = Q3 + 1.5 * IQR

outlier = df[(df['salary'] < below) | (df['salary'] > above)]
outlier

Empty DataFrame
Columns: [salary]
Index: []

### Q57. Handle outliers using clipping.
> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

---

In [ ]:
df

lo = 20000
hi = 40000

df['salary'].clip(lower=lo , upper=hi)

0    20000
1    20000
2    30000
3    40000
4    40000
5    40000
Name: salary, dtype: int64

### Q58. Standardize column names.
> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

---

In [ ]:
data.name = data.name.str.strip().str.lower().str.replace(' ','_')
data

               name
0         ajay_more
1  subodh_savarekar
2     swapnil_tambe

### Q59. Handle mixed data types in a column.
> 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

---

In [ ]:
df = pd.DataFrame({'age': ['25','30','unknown','45','na','50']})
df
pd.to_numeric(df['age'],errors='coerce')

0    25.0
1    30.0
2     NaN
3    45.0
4     NaN
5    50.0
Name: age, dtype: float64

### Q60. Remove special characters from text data.
> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

---

In [ ]:
df = pd.DataFrame({'Text': ['Hello@123!', 'Python#3.9', 'Data-Science$', 'AI & ML']})
df['Text'].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)

0       Hello123
1       Python39
2    DataScience
3         AI  ML
Name: Text, dtype: object

## 🔹 Section 4: Data Manipulation (Q61–Q80)

---

### Q61. Filter rows using AND condition.
> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

---

In [ ]:
df = pd.DataFrame({'age':[25,30,35,40] , 'city':['mumbai','delhi','banglore','mumbai']})
df[(df['age'] > 30) & (df['city'] == 'mumbai')]

   age    city
3   40  mumbai

### Q62. Filter rows using OR condition.
> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

---

In [ ]:
df[(df['age'] > 30) | (df['city'] == 'mumbai')]

   age      city
0   25    mumbai
2   35  banglore
3   40    mumbai

### Q63. Filter rows using NOT condition.
> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

---

In [ ]:
df[~(df['city'] == 'mumbai')]

   age      city
1   30     delhi
2   35  banglore

### Q64. Sort DataFrame by column values.
> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

---

In [ ]:
df.sort_values('age',ascending=False)

   age      city
3   40    mumbai
2   35  banglore
1   30     delhi
0   25    mumbai

### Q65. Sort DataFrame by index.
> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

---

In [ ]:
df.sort_index(axis=1)

   age      city
0   25    mumbai
1   30     delhi
2   35  banglore
3   40    mumbai

### Q66. Add calculated column.
> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

---

In [ ]:
df = pd.DataFrame({'price': [100,200,300] , 'quantity': [2,3,4]})
df['total'] = df['price'] * df['quantity']
df

   price  quantity  total
0    100         2    200
1    200         3    600
2    300         4   1200

### Q67. Remove column using `drop()`.
> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

---

In [ ]:
data = pd.DataFrame({'name': ['ajay','swapnil','subodh'] , 'age': [25,30,35] , 'city': ['palghar','rajgurunagar','savara']})
data.drop(columns='city')
data.drop(columns=['age' , 'city'])

      name
0     ajay
1  swapnil
2   subodh

### Q68. Remove rows using `drop()`.
> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

---

In [ ]:
data.drop(index=[0,1])

     name  age    city
2  subodh   35  savara

### Q69. Use `map()` on a column.
> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

---

In [ ]:
df = pd.DataFrame({'grades':['a','b','a','c']})
df['grades'].map({'a':3 , 'b':2 , 'c':1})

0    3
1    2
2    3
3    1
Name: grades, dtype: int64

### Q70. Apply function using `apply()`.
> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

---

In [ ]:
df = pd.DataFrame({'number':[2,3,4,5]})
df['square'] = df['number'].apply(lambda x : x ** 2)
df

   number  square
0       2       4
1       3       9
2       4      16
3       5      25

### Q71. Apply element-wise using `applymap()` / `map()`.
> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

---

In [ ]:
multi = df['number'].map(lambda x : x * 10)
multi

0    20
1    30
2    40
3    50
Name: number, dtype: int64

### Q72. Chain multiple operations.
> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

---

### Q73. Normalize numeric columns (Min-Max).
> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].

---

In [ ]:
df = pd.DataFrame({'a':[10,20,30] , 'b':[40,50,60]})

(df["a"] - df["b"].min()) / (df["a"].max() - df["b"].min())

0    3.0
1    2.0
2    1.0
Name: a, dtype: float64

### Q74. Scale numerical data (Z-score standardization).
> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

---

In [ ]:
(df["a"] - df["b"].mean()) / df["a"].std()

0   -4.0
1   -3.0
2   -2.0
Name: a, dtype: float64

### Q75. Rank values in a column.
> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

---

In [ ]:
data['age'].rank(ascending=False)

0    3.0
1    2.0
2    1.0
Name: age, dtype: float64

### Q76. Create bins using `cut()`.
> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

---

In [ ]:
df = pd.DataFrame({'Score': [10, 25, 40, 55, 70, 85, 95]})
df['cut_bins'] = pd.cut(df["Score"], bins=4)
df

   Score        cut_bins
0     10  (9.915, 31.25]
1     25  (9.915, 31.25]
2     40   (31.25, 52.5]
3     55   (52.5, 73.75]
4     70   (52.5, 73.75]
5     85   (73.75, 95.0]
6     95   (73.75, 95.0]

### Q77. Create bins using `qcut()`.
> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

---

In [ ]:
df['qcut_bins'] = pd.qcut(df["Score"], q=4 , labels=["Q1","Q2","Q3","Q4"])
df

   Score        cut_bins qcut_bins
0     10  (9.915, 31.25]        Q1
1     25  (9.915, 31.25]        Q1
2     40   (31.25, 52.5]        Q2
3     55   (52.5, 73.75]        Q2
4     70   (52.5, 73.75]        Q3
5     85   (73.75, 95.0]        Q4
6     95   (73.75, 95.0]        Q4

### Q78. Count unique values.
> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

---

In [ ]:
df = pd.DataFrame({'number': [10,20,30,10,40,20,50,30]})
df['number'].nunique()
df['number'].value_counts()

number
10    2
20    2
30    2
40    1
50    1
Name: count, dtype: int64

### Q79. Replace multiple values at once.
> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

---

In [ ]:
df['new_num'] = df.replace([40,50],100)
df

   number  new_num
0      10       10
1      20       20
2      30       30
3      10       10
4      40      100
5      20       20
6      50      100
7      30       30

### Q80. Create flag column based on condition.
> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

---

In [ ]:
df = pd.DataFrame({'Score': [45, 72, 88, 60, 95]})
np.where(df['Score'] > 70,1,0)

array([0, 1, 1, 0, 1])

## 🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

---

### Q81. Iterate over rows using `iterrows()`.
> 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.

---

### Q82. Iterate using `itertuples()`.
> 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

---

### Q83. Iterate over columns.
> 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

---

### Q84. Avoid iteration using vectorization.
> 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

---

### Q85. Group data using `groupby()`.
> 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

---

### Q86. Calculate sum per group.
> 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

---

### Q87. Calculate multiple aggregations.
> 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

---

### Q88. Group by multiple columns.
> 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

---

### Q89. Filter grouped data.
> 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.

---

### Q90. Transform grouped data using `transform()`.
> 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.

---

### Q91. Apply custom function in groupby.
> 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

---

### Q92. Create basic pivot table.
> 💡 **Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

---

### Q93. Use multiple aggregation functions in pivot.
> 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

---

### Q94. Handle missing values in pivot tables.
> 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

---

### Q95. Add margins (totals) in pivot tables.
> 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

---

### Q96. Create multi-level pivot table.
> 💡 **Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.

---

### Q97. Convert DataFrame to pivot format.
> 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

---

### Q98. Compare pivot vs groupby.
> 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

---

### Q99. Build summary report using pivot table.
> 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

---

### Q100. Create an end-to-end analysis workflow.
> 💡 **Hint:** Follow this pipeline:  
> 1. Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

---

*📌 Remember: Try solving without hints first. Look at hints only when genuinely stuck.*